server {
  listen 80 default_server;
  server_name immich.carlosjg.space;

  location = /healthz {
    access_log off;
    default_type text/plain;
    return 200 "ok\n";
  }

  location / {
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;
    set $upstream immich-server:2283;
    proxy_pass http://$upstream;
  }
}

server {
  listen 5984;
  server_name couchdb.carlosjg.space;

  location / {
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;
    set $upstream couchdb:5984;
    proxy_pass http://$upstream;
  }
}
